/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DebugLogger: typeof import('./components/logger').DebugLogger
  const LitElement: typeof import('lit').LitElement
  const PaymentBottomSheet: typeof import('./components/payment-bottom-sheet').PaymentBottomSheet
  const TW: typeof import('./mixins/tailwind-integration').TW
  const Task: typeof import('@lit/task').Task
  const TaskStatus: typeof import('@lit/task').TaskStatus
  const UiDrawer: typeof import('./components/drawer').UiDrawer
  const consume: typeof import('@lit/context').consume
  const createContext: typeof import('@lit/context').createContext
  const css: typeof import('lit').css
  const customElement: typeof import('lit/decorators.js').customElement
  const decode: typeof import('./utils/decode').decode
  const html: typeof import('lit').html
  const logger: typeof import('./utils/logger').logger
  const loggerContext: typeof import('./contexts/logger.context').loggerContext
  const map: typeof import('lit/directives/map.js').map
  const nothing: typeof import('lit').nothing
  const portal: typeof import('./utils/portal').portal
  const property: typeof import('lit/decorators.js').property
  const provide: typeof import('@lit/context').provide
  const query: typeof import('lit/decorators.js').query
  const render: typeof import('lit').render
  const request: typeof import('./libs/request').request
  const state: typeof import('lit/decorators.js').state
  const tv: typeof import('./libs/tv').tv
  const validateCRC: typeof import('./utils/decode').validateCRC
  const validateEmvcoQR: typeof import('./utils/decode').validateEmvcoQR
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EmvcoResult, Decode } from './utils/decode'
  import('./utils/decode')
  // @ts-ignore
  export type { NativeData, DataFactory, RequestOptions } from './libs/request'
  import('./libs/request')
  // @ts-ignore
  export type { ExtractSlots, ExtractUi } from './libs/tv'
  import('./libs/tv')
  // @ts-ignore
  export type { LogLevel, ILogger } from './contexts/logger.context'
  import('./contexts/logger.context')
  // @ts-ignore
  export type { UiDrawer } from './components/drawer'
  import('./components/drawer')
  // @ts-ignore
  export type { DebugLogger } from './components/logger'
  import('./components/logger')
  // @ts-ignore
  export type { PaymentBottomSheet } from './components/payment-bottom-sheet'
  import('./components/payment-bottom-sheet')
  // @ts-ignore
  export type { LitMixin } from './mixins/tailwind-integration'
  import('./mixins/tailwind-integration')
}
