/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DebugLogger: typeof import('./components/logger').DebugLogger
  const LitElement: typeof import('lit').LitElement
  const PaymentBottomSheet: typeof import('./components/payment-bottom-sheet').PaymentBottomSheet
  const PaymentSelectorDrawer: typeof import('./components/payment-selector-drawer').PaymentSelectorDrawer
  const QrisScanner: typeof import('./components/qris-scanner').QrisScanner
  const Router: typeof import('@lit-labs/router').Router
  const Routes: typeof import('@lit-labs/router').Routes
  const TW: typeof import('./mixins/tailwind-integration').TW
  const Task: typeof import('@lit/task').Task
  const TaskStatus: typeof import('@lit/task').TaskStatus
  const TransactionErrorDialog: typeof import('./components/transaction-error-dialog').TransactionErrorDialog
  const UiDrawer: typeof import("./components/ui/drawer").UiDrawer
  const consume: typeof import('@lit/context').consume
  const createContext: typeof import('@lit/context').createContext
  const createRef: typeof import('lit/directives/ref.js').createRef
  const css: typeof import('lit').css
  const customElement: typeof import('lit/decorators.js').customElement
  const decode: typeof import('./utils/decode').decode
  const formatRupiah: typeof import('./utils/format').formatRupiah
  const getAppId: typeof import('./utils/wx').getAppId
  const html: typeof import('lit').html
  const logger: typeof import('./utils/logger').logger
  const loggerContext: typeof import('./contexts/logger.context').loggerContext
  const map: typeof import('lit/directives/map.js').map
  const nothing: typeof import('lit').nothing
  const portal: typeof import('./directives/portal').portal
  const property: typeof import('lit/decorators.js').property
  const provide: typeof import('@lit/context').provide
  const query: typeof import('lit/decorators.js').query
  const ref: typeof import('lit/directives/ref.js').ref
  const render: typeof import('lit').render
  const request: typeof import('./libs/request').request
  const routerContext: typeof import('./contexts/router.context').routerContext
  const state: typeof import('lit/decorators.js').state
  const tv: typeof import('./libs/tv').tv
  const validateCRC: typeof import('./utils/decode').validateCRC
  const validateEmvcoQR: typeof import('./utils/decode').validateEmvcoQR
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EmvcoResult, Decode } from './utils/decode'
  import('./utils/decode')
  // @ts-ignore
  export type { NativeData, DataFactory, RequestOptions } from './libs/request'
  import('./libs/request')
  // @ts-ignore
  export type { ExtractSlots, ExtractUi } from './libs/tv'
  import('./libs/tv')
  // @ts-ignore
  export type { LogLevel, ILogger } from './contexts/logger.context'
  import('./contexts/logger.context')
  // @ts-ignore
  export type { AppRouter } from './contexts/router.context'
  import('./contexts/router.context')
  // @ts-ignore
  export type { DebugLogger } from './components/logger'
  import('./components/logger')
  // @ts-ignore
  export type { PaymentBottomSheet } from './components/payment-bottom-sheet'
  import('./components/payment-bottom-sheet')
  // @ts-ignore
  export type { PaymentSelectorDrawer } from './components/payment-selector-drawer'
  import('./components/payment-selector-drawer')
  // @ts-ignore
  export type { QrisScanner } from './components/qris-scanner'
  import('./components/qris-scanner')
  // @ts-ignore
  export type { TransactionErrorDialog } from './components/transaction-error-dialog'
  import('./components/transaction-error-dialog')
  // @ts-ignore
  export type { LitMixin } from './mixins/tailwind-integration'
  import('./mixins/tailwind-integration')
}
